# -*- coding: utf-8 -*-
"""Day2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zBsbaCKy7Le0ah27QUXNQ9NO873r49UV
"""

a=8
b=10
print(a+b)



d=a*b
print(d)

a=float(input('Enter Number1 is '))
b=float(input('Enter Number 2 is  '))


ad=a+b
diff=a-b
mul=a*b
div=a/b
mod=a%b
print("sum:{0},Sub:{1},Mul:{2},Div:{3},Mod:{4}".format(ad,diff,mul,div,mod)) # print using arguments and format is used to mapped arguments 
print("sum :%d, Sub :%f, Mul:%d , Div:%25.3f, Mod:%d"  %(ad,diff,mul,div,mod)) # % using specific n data types 
# 25 means padding # .3 means number of decimal point of points # how many digits after the dot
print("Sum:{0}".format(mod))




c=int(input("Enter number here ")) ;
d= int(input("Enter number here "));
e= c+d ;
print("enter numbers are {0} and {1}".format(c,d));

print("{0:<1} | {1:<4} ".format('sum','diff')) #< left or right alignment    <4---> padding space
print("{0} | {1} ".format('sum','diff'))

s='S'
text='Dhanushka'
print(s*5)

print(text[4:])
print(text[:5])
print(text[:2])
print(text[-1])
print(text[6:-1])

a='Master Class'
print(a.upper())
b= a.split()
print(b[0])
print(b[1])
c=a.split('e')
print(c[0])
print(c[1])

d='Dhanushka,Prasanna,Gunasinghe'
e=d.split(',')
print(e)
print(e[2])

print('This is {0} '.format(b[1]))
print(f'This is {b[0]}')

a=[1,2,3,4]
b=['champ',22.3,1]
print(len(a))
print(a[2])
print(a+b)
b.reverse()
c=[a,b]
print(c[0][0])
print(c)


d={"Name":"Elon", "Age":50,"Company":["spaceX","Tesla"]}
print(d)
print(d["Name"])
print(d["Age"])
d["Age"]=52
print(d)
e={"climate":{"condition":{"temparature":"38","huminity":"54"}}}
print(e["climate"]["condition"]["huminity"])

f={"Name":{"Age":25}}
print(f["Name"]["Age"])

print(d.keys())
print(f.keys())
print(e.keys())
print(e.values())
print(e.items())
h={ }



a = [10,20,'test']
a[1]='test1'
print(a[2])
a.append("test1")
print(a)

a= (10,10,'test','test1')
print(a)

mytuple = ("apple", "banana", "cherry")
print(type(mytuple))
print(mytuple)
fruits= (green, yellow, red)
(green, yellow, red) = fruits
print(green)

a={'test','test3',1,2}
print(a)


print(a)
print(type(a))

thisset = set(("apple", "banana", "cherry")) # note the double round-brackets
print(thisset)

a={'test',2,3}
print(a)

print(type(a))

a={name:'tets'}
print(a)

